### ISSUE TITLE
[sentences/a 4-words sentence] incorrect sequence of exercise numbers

### ISSUE THREAD

**Issue by SiamionavaV** [Brain-up/brn#1664]
Preconditions:
1 Log in as an existing user. Open: groups/speech exercises/sentences/a 4-words sentence
https://brainup.site/groups/2/series/4/subgroup/31

Step:
1. Select "Understand a 4-words sentences from 12"
2 Execute the first 3 exercise

Actuai result: next number is 7
Expected result: next number is 4
![chrome_4jm59v4F6q](https://user-images.githubusercontent.com/79014501/110279397-1ff29b00-7fea-11eb-98c1-6748c39feb8b.png)

**Comment by Micirin** [comment]
done

**Comment by SFin-tech** [comment]
not corrected

**Comment by koylubaevnt** [comment]
@SFin-tech could you show how to open this page?
Is it EN or RU?

**Comment by HappyEgoiste** [comment]
As of Jan 18, 2023 not yet fixed. 1, 2, 3, 7 order in RU https://brainup.site/groups/2/series/4/subgroup/57
